kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster1
networking:
  ipFamily: ipv4
  apiServerAddress: "127.0.0.1"
# podSubnet: "10.244.0.0/16" #original
  podSubnet: "192.168.0.0/16"
# serviceSubnet: "10.96.0.0/12"
  # the default CNI will not be installed
  # so you can use Calico
  disableDefaultCNI: true

nodes:

- role: control-plane
  # Necessary to explore port
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"

  extraMounts:
  - hostPath: /srv/kind
    containerPath: /srv/kind 
   # optional: if set, the mount is read-only.
    # default false
    readOnly: false
    # optional: if set, the mount needs SELinux relabeling.
    # default false
    selinuxRelabel: false

  extraPortMappings:
  - containerPort: 80
    hostPort: 8080
    listenAddress: "127.0.0.1" # Optional, defaults to "0.0.0.0"
    protocol: TCP # Optional, defaults to tcp
  - containerPort: 443
    hostPort: 3443

- role: worker

- role: worker
